Controllers/RemediosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using PossoBeber.Models;

namespace PossoBeber.Controllers
{
    public class RemediosController : Controller
    {
       public IActionResult Lista(){

            RemediosRepository ur = new RemediosRepository();
            List<Remedios> lista = ur.Listar();
            return View(lista);
            
        }
        [HttpPost]
        public IActionResult Buscar(string Nome){

            RemediosRepository ur = new RemediosRepository();
            List<Remedios> lista = ur.Buscar(Nome);                       
            return View(lista);
            
        }          

        public IActionResult Excluir(int Id){

            //Validando se o usuario esta logado
            if(HttpContext.Session.GetInt32("IdUsuario")==null){
                return RedirectToAction("Login","Usuario");
            } 
            
            RemediosRepository pt = new RemediosRepository();
            Remedios remedioEncontrado = pt.BuscarPorId(Id);

            
            if (remedioEncontrado.Id>0){
                pt.remover(remedioEncontrado);
            } else
            {
                ViewData["mensagem"] = "Medicamento não localizado";
            }

            return RedirectToAction("Lista");

        }

        public IActionResult Inserir(){

            if(HttpContext.Session.GetInt32("IdUsuario")==null){
                return RedirectToAction("Login","Usuario");
            } 
            
            return View();

        }

        [HttpPost]
        public IActionResult Inserir(Remedios novoRemedio){
            
            RemediosRepository pt = new RemediosRepository();
            pt.inserir(novoRemedio);
            
            ViewData["mensagem"] = "Medicamento cadastrado com sucesso";
            return View();

        }

        public IActionResult Alterar(int Id){

            //Validando se o usuario esta logado
            if(HttpContext.Session.GetInt32("IdUsuario")==null){
                return RedirectToAction("Login","Usuario");
            } 

            RemediosRepository pt = new RemediosRepository();
            Remedios remedioEncontrado = pt.BuscarPorId(Id);

            return View(remedioEncontrado);

        }

        [HttpPost]
        public IActionResult Alterar(Remedios remedio){

            RemediosRepository pt = new RemediosRepository();
            pt.atualizar(remedio);

            return RedirectToAction("Lista");

        }   

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - POSSO BEBER?</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">POSSO BEBER?</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Remedios" asp-action="Lista">Tabela</a>
                        </li>
                         
                        @if (Context.Session.GetInt32("IdUsuario")==null)
                        {  //usuario deslogado ve isso
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                        </li> 
                        }  else{ //usuario logado ve isso
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Remedios" asp-action="Inserir">Cadastrar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Lista">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Sair</a>
                            </li>                        
                        }                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container text-center">
            &copy; 2022 - POSSO BEBER? - <a asp-area="" asp-controller="Usuario" asp-action="Inserir">Cadastre-se como colaborador</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>